cd ~/Desktop/sp8004/agent-aura-sovereign/spl_8004

# Anchor projesi initialize et
anchor init --no-git spl_8004_temp
mv spl_8004_temp/Anchor.toml .
rm -rf spl_8004_temp

# Anchor.toml'i düzenle
sed -i '' 's/spl_8004_temp/spl_8004/g' Anchor.toml

# Build
rm -rf Cargo.lock && cargo +stable generate-lockfile && \
sed -i '' 's/version = 4/version = 3/' Cargo.lock && \
anchor build
