name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  vercel-deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd agent-aura-sovereign || true
          npm ci --no-audit --no-fund

      - name: Build
        run: |
          cd agent-aura-sovereign || true
          npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # required
          vercel-args: '--prod'
          working-directory: 'agent-aura-sovereign'
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # optional but recommended
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # optional but recommended
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
